### ISSUE TITLE
kazam 1.5.3 'NX-72307' not working on ubuntu 18.04 

### ISSUE THREAD

**Issue by OsmanKandemir** [tuanphpvn/kazam#5]
Python Type Error:

TypeError: get() got an unexpected keyword argument 'raw'

Solution:
JUST ADDING **KWARGS TO THE PARAMETERS WILL SOLVE THE PROBLEM.

1-Open file

/usr/lib/python3/dist-packages/kazam/backend/config.py

or

/usr/local/lib/python3.6/dist-packages/kazam/backend/config.py

2-Find this function

def get(self, section, key):

and replace

def get(self, section, key,**kwargs):

3-Find this return line

return ConfigParser.get(self, section, key)

and replace

return ConfigParser.get(self, section, key,**kwargs)
